name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the Repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start &

      - name: Wait for app to be ready
        run: |
          echo "Waiting for the app to be ready..."
          sleep 5 # Adjust the sleep duration as needed
          curl --fail http://localhost:8080 || (echo "App failed to start" && exit 1)

      - name: Run tests
        run: npm test
